from pydantic import BaseModel, Field
from typing import Optional, List

class Campaign(BaseModel):
    """
    Pydantic model for a Campaign.
    Represents a game campaign run by a user, potentially using elements from Worlds, Items, and Characters.
    """
    id: Optional[str] = Field(None, description="Unique identifier for the campaign (generated by database)")
    user_id: str = Field(..., description="ID of the user who owns this campaign")
    name: str = Field(..., description="Name of the campaign")
    description: Optional[str] = Field(None, description="Description of the campaign")
    world_id: Optional[str] = Field(None, description="Optional ID of the primary world used in this campaign")
    characters: Optional[List[str]] = Field([], description="List of Character IDs involved in the campaign")
    items: Optional[List[str]] = Field([], description="List of Item IDs relevant to the campaign")
    # Add fields for campaign progress, notes, etc.

    class Config:
        orm_mode = True

class CampaignCreate(BaseModel):
    """
    Pydantic model for creating a new Campaign.
    Excludes the ID.
    """
    name: str = Field(..., description="Name of the campaign")
    description: Optional[str] = Field(None, description="Description of the campaign")
    world_id: Optional[str] = Field(None, description="Optional ID of the primary world used in this campaign")
    characters: Optional[List[str]] = Field([], description="List of Character IDs involved in the campaign")
    items: Optional[List[str]] = Field([], description="List of Item IDs relevant to the campaign")

class CampaignUpdate(BaseModel):
    """
    Pydantic model for updating an existing Campaign.
    All fields are optional.
    """
    name: Optional[str] = Field(None, description="New name for the campaign")
    description: Optional[str] = Field(None, description="New description of the campaign")
    world_id: Optional[str] = Field(None, description="Optional ID of the primary world used in this campaign")
    characters: Optional[List[str]] = Field(None, description="New list of Character IDs involved in the campaign") # Use None to allow replacing the list
    items: Optional[List[str]] = Field(None, description="New list of Item IDs relevant to the campaign") # Use None to allow replacing the list

