from pydantic import BaseModel, Field
from typing import Optional, List

class Character(BaseModel):
    """
    Pydantic model for a Character.
    Represents a character (NPC or PC) in a world or campaign.
    """
    id: Optional[str] = Field(None, description="Unique identifier for the character (generated by database)")
    user_id: str = Field(..., description="ID of the user who owns this character")
    world_id: Optional[str] = Field(None, description="Optional ID of the world this character belongs to")
    name: str = Field(..., description="Name of the character")
    description: Optional[str] = Field(None, description="Description or backstory of the character")
    stats: Optional[dict] = Field(None, description="JSON field for character stats (e.g., strength, dexterity)")
    inventory: Optional[List[str]] = Field([], description="List of Item IDs the character possesses")
    # Add other character-specific fields

    class Config:
        orm_mode = True

class CharacterCreate(BaseModel):
    """
    Pydantic model for creating a new Character.
    Excludes the ID.
    """
    world_id: Optional[str] = Field(None, description="Optional ID of the world this character belongs to")
    name: str = Field(..., description="Name of the character")
    description: Optional[str] = Field(None, description="Description or backstory of the character")
    stats: Optional[dict] = Field(None, description="JSON field for character stats")
    inventory: Optional[List[str]] = Field([], description="List of Item IDs the character possesses")

class CharacterUpdate(BaseModel):
    """
    Pydantic model for updating an existing Character.
    All fields are optional.
    """
    world_id: Optional[str] = Field(None, description="Optional ID of the world this character belongs to")
    name: Optional[str] = Field(None, description="New name for the character")
    description: Optional[str] = Field(None, description="New description or backstory of the character")
    stats: Optional[dict] = Field(None, description="New JSON field for character stats")
    inventory: Optional[List[str]] = Field(None, description="New list of Item IDs the character possesses") # Use None to allow replacing the list

